# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest ${{ secrets.USERNAME }}/myapp:latest

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.USERNAME }}/myapp:latest

      - name: Deploy Docker container
        run: |
          docker stop myapp || true
          docker rm myapp || true
          docker run -d -p 3000:3000 --name myapp ${{ secrets.USERNAME }}/myapp:latest
